"""
Los Angeles industrial financing vertical -- 9 curated submarkets.

Feeds la_industrial_page.html and la_industrial_index.html at
/industrial/la/{slug}.html (round 2, authored 2026-07-11 via parallel
agent fan-out against a fact-checked LA industrial regulatory brief:
SCAQMD WAIRE Program, Port Clean Air Action Plan, Alameda Corridor,
FTZ 202, City of LA M1/M2/M3 zoning). Same shape as la_vertical.py's
RAW_HOODS/build_hoods()/build_hood_groups()/nearby_hoods() so generate.py
wiring is identical between verticals.
"""

REGION_ORDER = ["South Bay & Harbor", "Vernon, Commerce & Central LA", "San Fernando Valley", "San Gabriel Valley", "Gateway Cities & Long Beach", "Inglewood & the Airport Corridor", "Mid-Counties", "South LA & Compton"]

RAW_HOODS = [
    {
        "name": "South Bay (Torrance, Carson, Gardena, Harbor Gateway)",
        "slug": "south-bay-industrial",
        "region": "South Bay & Harbor",
        "product_type": "Infill logistics and distribution",
        "overview": "The South Bay ranks among the largest infill industrial markets in the country, and it reads that way on the ground: mile after mile of small-to-mid bay buildings across Torrance, Carson, Gardena, and the Harbor Gateway corridor, much of it decades old and effectively impossible to replicate given how little vacant industrial land remains. Clear heights and dock configurations skew older than the big-box product built further inland, which suits the submarket's core tenant base of last-mile e-commerce operators, regional third-party logistics providers, and light manufacturers who value infill locations over new construction. The area also carries a genuine aerospace-adjacent manufacturing legacy, with a long-standing base of precision manufacturers, machine shops, and parts suppliers still operating alongside newer logistics and distribution tenants.\n\nVacancy has stayed structurally tight for years because there is so little land left to build on; most new supply comes from redevelopment of older sites rather than ground-up construction. Access is a real advantage: the 110, 405, and 91 freeways run through the submarket, and the short haul to the Ports of Los Angeles and Long Beach makes South Bay buildings attractive to import-dependent users who want to stage inventory near the docks without paying full port-adjacent rents. Gardena and Harbor Gateway lean smaller-bay and owner-user in character, while inland Carson near the 110 and 91 interchange carries a mix of larger distribution buildings; Carson's port-facing side, covered separately as part of the Gateway Cities submarket, runs a different container and drayage profile entirely.",
        "financing_playbook": "We see more owner-user activity in the South Bay than almost any other LA industrial submarket, a direct result of all that small-to-mid bay stock: manufacturers, machine shops, and logistics operators buying the buildings they occupy rather than leasing. SBA 504 and 7(a) financing shows up constantly on these deals alongside conventional bank and credit union lending, typically in the $1M to $10M range for a single small-bay building. Investor and 1031 exchange buyers remain active too, especially for multi-tenant business parks near the 110 and 91, and bridge financing gets used often, both for value-add repositioning of older buildings and for fast-closing acquisitions where a conventional lender's timeline would cost the buyer the deal.",
        "watch_items": "Zoning across the South Bay runs the normal light-to-heavy industrial spectrum, administered separately by Torrance, Carson, and Gardena, with the Harbor Gateway pocket falling under the City of Los Angeles's own industrial framework; none of it should be assumed uniform parcel to parcel. The submarket's larger distribution buildings, generally the fewer buildings pushing past 100,000 square feet near the 110 and the harbor, fall within reach of the SCAQMD's WAIRE Program, which asks bigger warehouse operators to either invest in zero-emission trucks, solar, and EV charging or pay a mitigation fee. Most of the submarket's small-bay stock sits well under that threshold.",
        "faqs": [
            {"q": "What kind of industrial buildings are typical in the South Bay?", "a": "Most of the South Bay's industrial stock is small-to-mid bay space built decades ago, generally under 50,000 square feet per building, with older clear heights and dock configurations than the big-box product built further inland. Torrance, Carson, and Gardena are dotted with multi-tenant business parks alongside standalone owner-user buildings, many tracing back to the area's aerospace-adjacent manufacturing history. Larger distribution buildings do exist, concentrated closer to the 110 and 91 freeways and the harbor, but they are the exception rather than the rule. That small-bay character is a big part of why the submarket draws so many owner-users, and why vacancy has stayed tight given how little vacant land remains to add supply of any size."},
            {"q": "Why is industrial vacancy so tight in the South Bay?", "a": "The South Bay is essentially built out. It was one of the first major industrial submarkets to develop in Los Angeles County, and decades later there is almost no vacant land left for ground-up construction, so new supply depends almost entirely on redevelopment or repositioning of older buildings rather than construction on raw sites. Demand has stayed durable at the same time: last-mile e-commerce operators want infill locations close to the region's dense population, import-dependent users want proximity to the Ports of Los Angeles and Long Beach, and long-tenured manufacturers and machine shops have little incentive to relocate. That mix of fixed supply and steady, diversified demand is what keeps vacancy structurally tighter here than in newer inland submarkets."},
        ],
        "seo": {
            "h1": "South Bay Industrial Real Estate Financing",
            "title": "South Bay Industrial Financing | Torrance, Carson, Gardena, CA",
            "meta_description": "Bridge, SBA, and investor financing for industrial and logistics buildings across the South Bay: Torrance, Carson, Gardena, and Harbor Gateway. Loans from $1M.",
        },
    },
    {
        "name": "Vernon and Commerce",
        "slug": "vernon-commerce-industrial",
        "region": "Vernon, Commerce & Central LA",
        "product_type": "Rail-served heavy industrial and manufacturing",
        "overview": "Vernon is unlike anywhere else in Los Angeles County: an incorporated city built almost entirely for industry, with a tiny residential population and a municipal identity organized around keeping heavy manufacturing running. Together with neighboring Commerce, it forms one of the region's oldest and most rail-oriented industrial corridors, sitting just southeast of downtown Los Angeles along a legacy of meat-packing, food processing, metals, and heavy manufacturing that goes back generations. Building stock here skews older and heavier than almost anywhere else in the county, with large-footprint plants, older heavy-industrial construction, and rail spurs built into sites in a way that newer suburban industrial parks were never designed for.\n\nThat rail orientation is a defining feature: both cities sit along the Alameda Corridor, the 20-mile rail expressway that consolidated roughly 200 at-grade crossings into a single grade-separated route connecting the Ports of Los Angeles and Long Beach to the transcontinental rail yards near downtown. The 5 and 710 freeways run close by, reinforcing the corridor's role as a connector between the ports, downtown Los Angeles, and points east. As older manufacturing and food-processing plants close or consolidate, infill redevelopment has become increasingly common, with investors and owner-users alike repositioning aging heavy-industrial buildings for modern logistics, food distribution, and light manufacturing use.",
        "financing_playbook": "Vernon and Commerce see a heavier mix of investor and developer capital than typical LA infill submarkets, largely because so much of the opportunity here is redevelopment: buying an aging plant, repositioning or partially demolishing it, and re-leasing or re-selling into modern logistics or food-distribution use. We structure bridge financing for exactly that kind of transitional deal, where a conventional lender wants a stabilized asset and the property is not there yet, typically in the $2M to $30M range depending on building size. Owner-users still show up, particularly food processors and manufacturers acquiring a plant to run their own operation, and SBA financing gets used on the smaller end of that range.",
        "watch_items": "Vernon and Commerce each administer their own municipal zoning rather than the City of Los Angeles's code, but both run a similar light-to-heavy industrial spectrum, and the older core of both cities leans toward the general and heavy end of that spectrum rather than light industrial. Rail-served sites along the Alameda Corridor carry real value for users with import/export volume, and some may qualify for consideration under Foreign Trade Zone 202, the region's FTZ designation, which can help importers defer or reduce customs duties. Larger plants approaching or exceeding 100,000 square feet may also fall within the SCAQMD's WAIRE Program on redevelopment or expansion.",
        "faqs": [
            {"q": "Is Vernon actually a residential city, or is it all industrial?", "a": "Vernon is genuinely almost entirely non-residential, an incorporated city of its own within Los Angeles County that was built and governed specifically to support heavy industry rather than housing. That distinguishes it from most of the industrial submarkets around it, where zoning has to balance manufacturing against nearby residential neighborhoods. In Vernon, that tension is far more limited, which is part of why heavy manufacturing, food processing, and meat-packing operations have concentrated there for generations without the same entitlement friction that residential-adjacent industrial areas face elsewhere in the county. Commerce, its neighbor to the east, has more of a mixed character but shares the same rail-served, heavy-industrial heritage."},
            {"q": "Why does the Alameda Corridor matter for financing a Vernon or Commerce property?", "a": "The Alameda Corridor is a rail expressway connecting the Ports of Los Angeles and Long Beach to the transcontinental rail yards near downtown Los Angeles, and Vernon and Commerce sit along that route. For a rail-served site, that access is a real operating advantage for tenants moving high volumes of freight, which in turn supports the property's long-term leasing and resale story, two things a lender underwrites closely on a bridge or value-add loan. It does not change zoning or entitlements on its own, but it is part of the location narrative CLS CRE builds into the underwriting package whenever a deal involves rail-served industrial product in this corridor."},
        ],
        "seo": {
            "h1": "Vernon and Commerce Industrial Real Estate Financing",
            "title": "Vernon and Commerce Industrial Financing | Los Angeles, CA",
            "meta_description": "Bridge, investor, and owner-user financing for rail-served industrial and manufacturing buildings in Vernon and Commerce, California. Loans from $1M.",
        },
    },
    {
        "name": "San Fernando Valley (Van Nuys, Sun Valley, Pacoima, North Hollywood)",
        "slug": "san-fernando-valley-industrial",
        "region": "San Fernando Valley",
        "product_type": "Aerospace-adjacent manufacturing, flex, and distribution",
        "overview": "The San Fernando Valley's industrial base is scattered across a handful of distinct pockets rather than one contiguous corridor: Van Nuys around its general aviation airport, Sun Valley and Pacoima along the freeway and rail corridor to the north, and North Hollywood toward the Valley's eastern edge. Van Nuys Airport anchors a genuine aviation and aerospace-adjacent manufacturing cluster, with machine shops, avionics suppliers, and aircraft maintenance and modification operators clustered around the field. Sun Valley and Pacoima carry a heavier, more traditional industrial character, building materials, metal fabrication, distribution, and manufacturing on larger parcels, while North Hollywood has increasingly attracted flex and creative-industrial product serving the entertainment and media businesses nearby.\n\nUnlike the port-adjacent submarkets to the south, most Valley industrial demand is homegrown: manufacturers, distributors, and service businesses supplying the Valley's own dense residential and commercial population rather than moving import cargo. Access runs along the 101 through North Hollywood and Studio City, the 170 connecting North Hollywood up through Sun Valley and Pacoima to the 5, and the 134 tying North Hollywood and Burbank together. Because so much of this industrial stock sits close to residential neighborhoods, the city's MR1 and MR2 buffer-zone designations, built for industrial uses adjacent to housing, show up more often here than in submarkets with less residential adjacency.",
        "financing_playbook": "Financing patterns vary block by block in the Valley, and we underwrite across all of them. Around Van Nuys Airport, owner-user aerospace and aviation suppliers are common buyers, and SBA 504 and 7(a) financing pairs naturally with conventional bank debt for those deals, typically $1M to $8M for a single building. Sun Valley and Pacoima see more investor and developer activity in larger distribution and manufacturing buildings, while North Hollywood's flex and creative-industrial product draws both owner-users in the entertainment-adjacent trades and investors converting older industrial buildings to higher-value flex use. CLS CRE arranges bridge financing across all of these profiles, particularly for buyers repositioning older buildings or closing quickly against a competitive bid.",
        "watch_items": "All four of these neighborhoods sit within the City of Los Angeles, so the city's M1 through M3 industrial framework and its MR1/MR2 buffer designations apply directly, and buffer-zone parcels near residential streets carry tighter restrictions on noise, hours, and use than general or heavy industrial parcels. Larger distribution buildings in Sun Valley and Pacoima that approach the 100,000-square-foot range can fall within the SCAQMD's WAIRE Program, though most Valley buildings, especially the smaller flex and aviation-adjacent product around Van Nuys, sit below that threshold. Buyers should confirm a given parcel's actual zoning rather than assuming based on the surrounding area's general character.",
        "faqs": [
            {"q": "What makes the Van Nuys Airport area different from other Valley industrial pockets?", "a": "Van Nuys Airport is a general aviation field, and the industrial product surrounding it reflects that: machine shops, avionics and parts suppliers, and aircraft maintenance and modification operators that need proximity to the runway and to each other. That is a meaningfully different tenant and buyer base than the distribution and manufacturing product in Sun Valley or Pacoima, and it tends to draw more owner-user activity, since aviation-adjacent businesses often prefer to control their own facility rather than lease. Building sizes here also skew smaller than the big-box distribution product found elsewhere in the Valley or further out in the San Gabriel Valley, which fits the specialized, lower-volume nature of aviation manufacturing and service work."},
            {"q": "Why does so much Valley industrial space sit close to residential neighborhoods?", "a": "The San Fernando Valley developed with industrial and residential uses woven closer together than in submarkets like Vernon or the South Bay, largely because the Valley's industrial base grew up to serve its own dense population rather than port or rail cargo. That proximity is a big part of why the city's MR1 and MR2 buffer-zone designations exist and why they show up so often in Van Nuys, Sun Valley, Pacoima, and North Hollywood: they are built to let industrial and manufacturing uses continue operating next to housing while placing tighter limits on noise, hours, and certain uses than a standalone heavy-industrial zone would carry. That framework shapes what buyers and lenders can assume about a given building's future flexibility."},
        ],
        "seo": {
            "h1": "San Fernando Valley Industrial Real Estate Financing",
            "title": "San Fernando Valley Industrial Financing | Van Nuys & Sun Valley",
            "meta_description": "Financing for industrial, flex, and aerospace-adjacent manufacturing buildings across Van Nuys, Sun Valley, Pacoima, and North Hollywood. Loans from $1M.",
        },
    },
    {
        "name": "San Gabriel Valley (City of Industry, Irwindale)",
        "slug": "san-gabriel-valley-industrial",
        "region": "San Gabriel Valley",
        "product_type": "Big-box logistics and distribution",
        "overview": "The San Gabriel Valley's industrial core is anchored by City of Industry, a city literally incorporated and built for industrial use, and neighboring Irwindale, and together they form one of the region's most important big-box logistics hubs. City of Industry's building stock runs from older manufacturing product to newer large-footprint distribution centers built for national and regional logistics users, with generous clear heights and truck court depth that the older infill submarkets closer to the urban core generally cannot match. Irwindale carries its own distinct legacy in aggregate and building-materials production, sand and gravel operations, and related heavy industrial use, alongside newer distribution product built on land as older aggregate operations wind down or reposition.\n\nFreeway access defines the submarket: the 60, 57, and 10 freeways converge in and around the area, giving distribution users fast connections east toward the Inland Empire and south toward Orange County as well as back into central Los Angeles. That access, combined with larger parcel sizes than most infill LA submarkets can offer, is why national and regional third-party logistics providers, e-commerce distributors, and manufacturers increasingly choose City of Industry and Irwindale over tighter infill locations when a deal calls for a genuinely large building. Both cities are separately incorporated and administer their own industrial zoning rather than following the City of Los Angeles's framework.",
        "financing_playbook": "Big-box logistics product in the San Gabriel Valley draws a more institutional buyer and lender pool than smaller infill submarkets, with life insurance companies, CMBS execution, and larger regional and national banks active on stabilized distribution buildings, typically well above $10M and often into the tens of millions for the largest boxes. Bridge financing plays a real role on the value-add side, repositioning older manufacturing buildings into modern distribution use or carrying a building through lease-up after a tenant vacates. Owner-user activity is real but secondary here, mostly among manufacturers and building-materials operators in Irwindale, where we have arranged financing alongside conventional bank debt on the smaller end of the size range.",
        "watch_items": "City of Industry and Irwindale each set their own municipal industrial zoning rather than following the City of Los Angeles's code, and given how large a share of the submarket's stock is big-box distribution, the SCAQMD's WAIRE Program is a live consideration on a meaningful share of buildings here, since the roughly 100,000-square-foot-and-up threshold catches far more buildings in this submarket than in smaller-bay infill markets closer to the urban core. Irwindale's aggregate and building-materials operators also carry their own distinct environmental and land-use considerations tied to that legacy industry, separate from the warehouse-specific rules affecting the submarket's newer logistics stock.",
        "faqs": [
            {"q": "Why is City of Industry such a significant industrial submarket?", "a": "City of Industry is unusual even by Los Angeles County standards: it was incorporated specifically to support industrial use, with almost no residential population to create the land-use friction that shapes entitlements in mixed residential-industrial areas. That, combined with larger parcel sizes than most infill LA submarkets and direct access to the 60, 57, and 10 freeways, has made it one of the region's primary big-box logistics hubs, attracting national and regional distribution users who need larger buildings than the smaller-bay stock in submarkets like the South Bay or the San Fernando Valley can offer. It functions less like a traditional city and more like a purpose-built logistics park at municipal scale, and CLS CRE sees a steady flow of big-box acquisition and refinance requests originate from exactly this submarket."},
            {"q": "What is distinctive about Irwindale's industrial base compared to the rest of the San Gabriel Valley?", "a": "Irwindale has a long-standing legacy in aggregate and building-materials production, sand and gravel operations that trace back generations and that still shape the city's industrial character today. That is a meaningfully different use profile than the big-box distribution product dominating City of Industry next door, and it means financing and underwriting on an Irwindale property often has to account for the site's industrial history and current use alongside the more standard logistics and distribution analysis that applies elsewhere in the San Gabriel Valley. As some of that legacy aggregate land repositions toward distribution and other industrial use over time, it adds a redevelopment dimension that pure big-box submarkets elsewhere in the region generally do not have."},
        ],
        "seo": {
            "h1": "San Gabriel Valley Industrial Real Estate Financing",
            "title": "San Gabriel Valley Industrial Financing | City of Industry, CA",
            "meta_description": "Financing for big-box logistics and distribution buildings in City of Industry and Irwindale, California, near the 60, 57, and 10 freeways. Loans from $1M.",
        },
    },
    {
        "name": "Gateway Cities (Long Beach, Carson)",
        "slug": "gateway-cities-industrial",
        "region": "Gateway Cities & Long Beach",
        "product_type": "Port-adjacent drayage, trucking, and container logistics",
        "overview": "The Gateway Cities submarket, anchored by Long Beach and the port-facing side of Carson (inland Carson near the 110 and 91 runs a more conventional business-park profile, covered separately under the South Bay submarket), is built around one function above all others: moving containers off the water and into the supply chain. Container yards, drayage-focused trucking terminals, and transload and distribution buildings dominate the building stock here, much of it configured for heavy truck circulation rather than passenger traffic, with generous yard space and trailer storage often as important to a site as the building itself. This is the closest industrial product in the county to the Port of Long Beach, and that proximity is the entire investment thesis: every mile of drayage haul saved is real money to a trucking operation running dozens of loads a day between the terminal gates and a nearby yard or warehouse.\n\nThe 710 freeway is the submarket's spine, carrying the bulk of container traffic north from the port toward the rail yards and inland markets, with the 91 and 110 providing additional connections through Long Beach and Carson. This is also where the Alameda Corridor begins: the rail expressway that carries containers from the ports to the transcontinental rail yards near downtown Los Angeles starts at its southern end right here. Because so much of this submarket sits close to residential neighborhoods in Long Beach, Carson, and Wilmington, truck routes and community concerns about diesel emissions and noise carry real weight in how new industrial development gets entitled and scrutinized.",
        "financing_playbook": "Buyers in the Gateway Cities skew toward two distinct profiles, and we work both sides regularly: institutional and private investors acquiring container yards, transload facilities, and drayage-terminal real estate as income property, and trucking and logistics operators buying the yard or building they run their own fleet from. CLS CRE sees owner-user activity concentrated among drayage and trucking companies acquiring their own terminal, often paired with SBA financing on deals in the $1M to $6M range, alongside larger conventional and bridge financing for investors acquiring bigger container-handling or distribution assets. Bridge lending shows up often here too, particularly when a buyer needs to close quickly on a hard-to-replace yard site or reposition an older building for modern drayage and transload use.",
        "watch_items": "Long Beach and Carson each administer their own municipal industrial zoning rather than the City of Los Angeles's code, and truck-route designations matter as much as underlying zoning here, since streets carrying heavy drayage traffic near residential interface zones draw real community scrutiny on new development or expanded operations. The Ports of Los Angeles and Long Beach have both stated a goal of a fully zero-emission drayage fleet by 2035 under their Clean Air Action Plan, a trend worth underwriting into any long-term drayage-dependent operation. Larger transload and distribution buildings approaching 100,000 square feet can fall within the SCAQMD's WAIRE Program, and import/export-heavy users near the port may also want to evaluate eligibility for Foreign Trade Zone 202.",
        "faqs": [
            {"q": "Why does the Alameda Corridor start in the Gateway Cities?", "a": "The Alameda Corridor is a 20-mile rail expressway built to consolidate what used to be roughly 200 separate at-grade rail crossings into a single grade-separated route connecting the Ports of Los Angeles and Long Beach to the transcontinental rail yards near downtown Los Angeles, and its southern end sits right here in the Gateway Cities, near the port terminals themselves. For a site in Long Beach or Carson, that proximity to both the ports and the start of the rail corridor is a real locational advantage for any user moving high container volumes, whether by truck or by rail. It is a big part of why this submarket functions differently from inland industrial markets that only have freeway access to work with."},
            {"q": "How do truck routes and community concerns affect industrial property in the Gateway Cities?", "a": "Because container yards, drayage terminals, and transload facilities generate constant heavy-truck traffic, and because so much of the Gateway Cities sits close to residential neighborhoods in Long Beach, Carson, and Wilmington, truck-route designations and community concern about diesel emissions and noise shape entitlement scrutiny on new or expanded industrial development in a way that does not apply as strongly to inland submarkets. That does not make development impossible, but buyers and lenders should expect closer review on projects that would meaningfully increase truck traffic near residential interface zones, and should factor the ports' ongoing push toward zero-emission drayage trucking into how they underwrite a long-term drayage-dependent tenant or operation."},
        ],
        "seo": {
            "h1": "Gateway Cities Industrial Real Estate Financing",
            "title": "Gateway Cities Industrial Financing | Long Beach & Carson, CA",
            "meta_description": "Financing for port-adjacent container, drayage, and distribution properties in Long Beach and Carson near the Port of Long Beach. Loans from $1M.",
        },
    },
    {
        "name": "Inglewood-Hawthorne (Aerospace Corridor)",
        "slug": "inglewood-hawthorne-aerospace",
        "region": "Inglewood & the Airport Corridor",
        "product_type": "Flex and R&D space alongside aerospace manufacturing",
        "overview": "Inglewood and Hawthorne sit on the southwest side of the Los Angeles Basin, just east of LAX and threaded by the 405 and 105 freeways, and the two cities carry one of the deepest aerospace and advanced-manufacturing legacies in the region. Hawthorne is anchored by SpaceX's headquarters and rocket-manufacturing campus near Hawthorne Municipal Airport, and the pull of that operation has built up a dense layer of precision machine shops, avionics suppliers, and advanced-manufacturing tenants that lease and own flex and R&D buildings throughout the surrounding blocks. Inglewood's industrial stock runs older and smaller-bay, much of it built during the mid-century aerospace boom, with clear heights and column spacing that read as flex space today more than big-box distribution.\n\nLand competition has intensified as Inglewood has redirected large tracts toward entertainment and mixed-use development around SoFi Stadium and the broader Hollywood Park site, squeezing the available industrial base and pushing pricing higher on what remains. Tenant demand splits between legacy aerospace and defense manufacturers, a growing bench of newer space and advanced-mobility companies drawn to the ecosystem SpaceX helped build, and last-mile distribution users capitalizing on proximity to LAX and the freeway network. Flex product with office buildout and R&D-friendly power and HVAC commands a premium over raw manufacturing shells, and owner-users in the precision-manufacturing trades still compete directly with investors for the smaller bay sizes that define both cities' industrial cores.",
        "financing_playbook": "Investor and developer activity leads deal flow in Inglewood and Hawthorne's industrial and flex market, with bridge lenders particularly active on buildings that need repositioning into modern flex and R&D space to capture demand from the aerospace and advanced-manufacturing supply chain that has grown up around SpaceX's Hawthorne operations. Life companies and CMBS lenders show up selectively on larger, fully stabilized flex portfolios, though building sizes here skew smaller than the big-box product further south and east. Regional banks and credit unions remain the most consistent source of capital for owner-users, frequently paired with SBA 504 or 7(a) financing when a precision-manufacturing or advanced-manufacturing operator is buying the building it occupies, and sale-leaseback structures are common among aerospace suppliers converting real estate equity into working capital. CLS CRE arranges financing from $1M up through large institutional checks across this mix.",
        "watch_items": "Industrial parcels in both cities are typically zoned M1 or M2, with smaller pockets of MR1/MR2 buffer zoning where industrial blocks sit closest to residential neighborhoods, narrowing the use list and tightening noise standards. Most buildings here fall well under the roughly 100,000-square-foot threshold that triggers SCAQMD's WAIRE Program, though the handful of larger distribution buildings near the 405/105 interchange should budget for it. Aerospace and advanced-manufacturing importers and exporters operating here may also want to evaluate Foreign Trade Zone 202 eligibility. Continued conversion of industrial-zoned land to entertainment and mixed-use around Hollywood Park is worth watching, since it is tightening the supply of replacement industrial sites in Inglewood.",
        "faqs": [
            {"q": "What kind of industrial space is available in the Inglewood and Hawthorne aerospace corridor?", "a": "Inglewood and Hawthorne offer a mix of legacy manufacturing buildings, converted flex and R&D space, and a smaller supply of last-mile distribution product. Much of the stock was built during the mid-century aerospace boom, so clear heights and bay depths run smaller than newer big-box submarkets, but the space suits precision manufacturers, avionics and advanced-mobility suppliers, and R&D users well. Space near SpaceX's Hawthorne headquarters and Hawthorne Municipal Airport draws steady interest from companies that want proximity to that ecosystem, while Inglewood's industrial pockets compete for land against the entertainment and mixed-use development spreading out from SoFi Stadium and Hollywood Park. Availability is limited and turnover is slow, so buyers and tenants often need to move quickly when space comes to market."},
            {"q": "How do lenders finance owner-user manufacturing buildings in Hawthorne and Inglewood?", "a": "Owner-users buying manufacturing or flex buildings in Hawthorne and Inglewood typically combine a conventional bank or credit union first mortgage with SBA 504 or 7(a) financing, which lets a buyer put down less cash while still owning the real estate that houses their operation. Deal sizes commonly start around $1M for smaller precision-manufacturing shops and climb well past that for larger flex or R&D buildings. Lenders will want to understand the tenant's aerospace or advanced-manufacturing supply chain relationships, since that context speaks directly to the durability of the operation. Commercial Lending Solutions works with owner-users throughout this corridor to structure financing that blends conventional and SBA sources, and to line up bridge capital when a building needs repositioning before it can qualify for permanent financing."},
        ],
        "seo": {
            "h1": "Inglewood-Hawthorne Aerospace Corridor Industrial Financing",
            "title": "Inglewood-Hawthorne Industrial Financing | CLS CRE",
            "meta_description": "Bridge, SBA, and institutional financing for flex, R&D, and manufacturing buildings across the Inglewood-Hawthorne aerospace corridor, for investors and owner-users alike.",
        },
    },
    {
        "name": "Mid-Counties (Santa Fe Springs, Cerritos)",
        "slug": "mid-counties-industrial",
        "region": "Mid-Counties",
        "product_type": "Big-box and mid-bay distribution",
        "overview": "Santa Fe Springs and Cerritos sit at the geographic center of the Mid-Counties industrial market, within a short haul of where the 5, 605, and 91 freeways come together east of downtown Los Angeles and just north of Orange County. That location is the submarket's defining advantage: a distributor based here can reach both Los Angeles and Orange County demand within a short haul, which has made the corridor one of the most consistently sought-after infill industrial locations in the county. Santa Fe Springs carries a long manufacturing history alongside its distribution stock, with older concrete tilt-up buildings from the 1960s and 1970s still doing productive work as plating shops, metal fabricators, and light manufacturers, interspersed with larger, more modern distribution buildings on redeveloped or expanded sites. Cerritos contributes a smaller, tighter industrial base alongside its retail and office development.\n\nTenant demand here spans national 3PLs and regional distributors serving the LA/OC corridor, import and wholesale distribution companies capitalizing on the freeway access, and a legacy base of owner-user manufacturers that have operated out of Santa Fe Springs for decades. Land is scarce and largely built out, so most new supply comes from teardown-and-rebuild redevelopment rather than ground-up construction on vacant land, and clear heights on newer product run well above what the older 1960s and 1970s stock offers. That scarcity keeps competition for available buildings and pad sites intense, whether the buyer is an institutional distribution user or a local manufacturer buying its own building.",
        "financing_playbook": "Mid-Counties distribution product draws a full range of capital. Life insurance companies and CMBS lenders actively compete for stabilized big-box buildings leased to credit tenants, while banks and credit unions dominate smaller mid-bay and owner-user manufacturing deals, often layering in SBA 504 or 7(a) financing for a Santa Fe Springs manufacturer buying its own building. Bridge lenders are especially active here given how much of the submarket's growth comes from value-add repositioning and redevelopment of older, functionally obsolete buildings into modern big-box product, with a stabilized takeout or sale-leaseback exit once the building is leased. Deal sizes commonly start at $1M for smaller owner-user buildings and extend well into nine figures for institutional-grade distribution assets, with investor and developer transactions leading the volume we see out of this corridor.",
        "watch_items": "Most large distribution buildings in Santa Fe Springs and Cerritos fall at or above the roughly 100,000-square-foot threshold that triggers SCAQMD's WAIRE Program, so buyers and developers of big-box product should budget for compliance points or the associated mitigation fee. Zoning runs primarily M1 and M2, with the usual conditional-use layers for higher-intensity manufacturing uses. Because land is scarce and largely built out, entitlement risk on redevelopment sites tends to center on parking, truck circulation, and neighboring-use compatibility rather than base zoning. Importers and distributors serving both county markets from here may also want to evaluate Foreign Trade Zone 202 eligibility given the volume of goods moving through the corridor.",
        "faqs": [
            {"q": "Why is the Mid-Counties industrial market around Santa Fe Springs and Cerritos so competitive?", "a": "Santa Fe Springs and Cerritos sit within a short haul of where the 5, 605, and 91 freeways come together, giving distributors based here quick access to both Los Angeles and Orange County demand from a single building. That central location, combined with a largely built-out land base, means very little new industrial supply gets added and existing buildings turn over quickly once they hit the market. Santa Fe Springs also carries decades of manufacturing history, so the tenant and owner-user base is unusually deep for a submarket this size. Investors, developers, and owner-users all compete for the same limited inventory, which keeps pricing firm and financing timelines tight, since buyers who cannot move quickly on financing risk losing the building to a more prepared buyer."},
            {"q": "What financing works best for a redevelopment or value-add industrial building in Santa Fe Springs or Cerritos?", "a": "Because so much of the Mid-Counties submarket's newer supply comes from tearing down or repositioning older 1960s and 1970s buildings rather than ground-up construction on vacant land, bridge financing is usually the right starting point. A bridge loan can fund the acquisition and the capital improvements needed to bring an older tilt-up building up to modern clear-height and loading standards, with a permanent loan or sale-leaseback exit once the building is leased to a stabilized tenant. CLS CRE structures these deals with an eye toward the eventual takeout, whether that means a life company or CMBS loan on a stabilized asset or an SBA-backed permanent loan if the end buyer is an owner-user."},
        ],
        "seo": {
            "h1": "Mid-Counties Industrial Financing: Santa Fe Springs & Cerritos",
            "title": "Mid-Counties Industrial Financing | Santa Fe Springs & Cerritos | CLS CRE",
            "meta_description": "Distribution, manufacturing, and redevelopment financing across the Santa Fe Springs and Cerritos industrial corridor near the 5/605/91 freeway interchange.",
        },
    },
    {
        "name": "South LA-Compton (Alameda Corridor)",
        "slug": "south-la-compton-industrial",
        "region": "South LA & Compton",
        "product_type": "Lower-basis distribution and light manufacturing",
        "overview": "South Los Angeles and Compton sit at the midpoint of the Alameda Corridor, the 20-mile rail expressway that consolidated freight rail traffic moving between the Ports of Los Angeles and Long Beach and the transcontinental rail yards near downtown. That position has anchored a deep base of distribution and light-manufacturing buildings along the rail-served blocks in Compton and the adjacent South LA industrial pockets, much of it built decades ago and carrying a meaningfully lower basis than comparable product closer to the ports or in the South Bay. The 110 runs along the western edge of this corridor through South LA, the 105 crosses Compton's northern edge, and the 710 lies a short distance east, giving distribution and trucking users multiple routes to the ports, the rail yards, and the broader county freeway grid.\n\nUnlike the more purely industrial pockets of the county, South LA and Compton's industrial stock sits tightly interwoven with dense residential neighborhoods, which shapes how these buildings get used and how new development gets entitled. Tenant demand here runs toward distribution, trucking and logistics operations, light manufacturers, and import-adjacent users drawn by the rail access and the comparatively low cost of entry. Building sizes skew smaller and older than the big-box product found further east, which keeps per-square-foot pricing accessible to owner-users and value-add investors even as institutional capital has increasingly pushed into the broader Gateway Cities industrial market chasing yield.",
        "financing_playbook": "The lower basis that defines South LA and Compton industrial product is the main draw for both value-add investors and owner-users, and financing here reflects that split. Bridge lenders are active on acquisition and reposition plays, especially older buildings that need functional upgrades before they can command market rent or qualify for permanent financing. Banks and credit unions handle much of the owner-user volume, frequently paired with SBA 504 or 7(a) loans for trucking, distribution, and light-manufacturing operators buying their own building. Life company and CMBS capital shows up selectively on larger, stabilized rail-served assets but is less common than in bigger-box submarkets given smaller average building size. We see deal sizes here starting around $1M, and sale-leaseback structures are used regularly by owner-operators looking to unlock capital tied up in real estate.",
        "watch_items": "Zoning across South LA's industrial pockets (City of Los Angeles) includes standard M1 through M3 designations along with MR1 and MR2 buffer zoning; Compton is a separately incorporated city administering its own municipal industrial zoning rather than the City of LA's code, so a similar light-to-heavy industrial spectrum applies there under different ordinance numbers. MR zoning is more common in this submarket than in most other LA industrial areas because industrial and residential uses sit so close together; MR zoning narrows the permitted use list and tightens noise standards. Truck routes serving rail yards and the broader corridor run through or near residential blocks, and community concern about diesel emissions and noise near housing shapes entitlement scrutiny on new or expanded industrial development. Trucking and logistics operators serving port drayage from here should also track the ports' ongoing push toward zero-emission drayage fleets, targeted for full conversion by 2035.",
        "faqs": [
            {"q": "What makes South LA and Compton industrial real estate different from other Los Angeles industrial submarkets?", "a": "South LA and Compton sit at the midpoint of the Alameda Corridor, the rail expressway connecting the Ports of Los Angeles and Long Beach to the transcontinental rail yards near downtown, which gives rail-served buildings here a genuine logistics advantage. The building stock is older and smaller-bay than the big-box product found in the Mid-Counties or Inland Empire, which keeps the basis meaningfully lower and makes the area attractive to value-add investors and owner-users who cannot compete for newer, larger buildings elsewhere. Because industrial blocks here sit close to dense residential neighborhoods, truck routing and noise are bigger considerations than in more purely industrial submarkets, and MR-zoned buffer parcels are more common. That combination of low basis and tight community interface defines how deals in this submarket actually get underwritten."},
            {"q": "Can I get SBA or owner-user financing for a manufacturing building in Compton or South LA?", "a": "Yes, and it is one of the more common financing paths in this submarket given how many buildings here are occupied by trucking, distribution, and light-manufacturing operators who own their real estate. SBA 504 and 7(a) programs typically pair with a conventional bank or credit union first mortgage, letting an owner-user put less cash into the deal while financing both the building and, in some cases, equipment or improvements. Lenders will look closely at the operating business's cash flow and time in business, not just the real estate, since SBA underwriting is fundamentally a business-qualification process. CLS CRE works with owner-users throughout Compton and South LA to structure this blended financing and to arrange bridge capital when a building needs work before it can qualify."},
        ],
        "seo": {
            "h1": "South LA & Compton Industrial Financing",
            "title": "South LA & Compton Industrial Financing | CLS CRE",
            "meta_description": "Bridge, SBA, and acquisition financing for lower-basis distribution and light-manufacturing buildings across South LA and Compton's Alameda Corridor industrial base.",
        },
    },
    {
        "name": "Sun Valley-Pacoima (Northeast San Fernando Valley)",
        "slug": "sun-valley-pacoima-industrial",
        "region": "San Fernando Valley",
        "product_type": "Recycling, building materials, and light manufacturing",
        "overview": "Sun Valley and Pacoima anchor the northeast corner of the San Fernando Valley's industrial base, a pocket that has always run a notch more utilitarian than the office-adjacent industrial product found closer to Burbank and the media studios to the south. The building stock here skews older and smaller-bay, built for function rather than image, and a meaningful share of it houses uses that do not fit neatly into a typical distribution building: metal and construction-material recyclers, building-material yards and suppliers, auto-related and equipment-service operators, and light manufacturers alongside more conventional local distribution tenants. The 5 and 210 freeways frame the area, with the 5 running along the eastern side toward Burbank and Sylmar and the 210 running along Pacoima's northern edge toward the foothill communities, giving trucking access without the port-adjacent congestion of the Harbor-area submarkets.\n\nThat utilitarian tenant mix and older building stock keep the basis in Sun Valley and Pacoima meaningfully below the rest of the San Fernando Valley industrial market, which has made the pocket a magnet for owner-users who could never compete for space in the Valley's larger, more institutional industrial nodes. Industrial parcels here also sit close to residential neighborhoods in places, which keeps noise, truck circulation, and outdoor-storage use in view of local entitlement review. For an investor or owner-operator willing to work with older, smaller buildings, the combination of low basis and steady blue-collar tenant demand has kept this pocket of the Valley functioning as one of the more affordable industrial footholds left in Los Angeles.",
        "financing_playbook": "Sun Valley and Pacoima are among the most owner-user-heavy industrial pockets CLS CRE sees in Los Angeles County, and financing here leads with that buyer profile rather than with institutional investors. Banks and credit unions anchor most deals, commonly paired with SBA 504 or 7(a) financing for recyclers, building-material suppliers, and light manufacturers purchasing the real estate their operating business runs from. Bridge financing shows up when a buyer needs to close quickly on a lower-basis building or fund improvements, such as yard paving, fencing, or outdoor-storage upgrades, before permanent financing can be placed. Life company and CMBS capital rarely reaches this far into the Valley given the smaller average building and loan size. Deal sizes commonly start near the $1M minimum and rarely reach the scale seen in the big-box Mid-Counties market, but volume and owner-user demand stay consistent.",
        "watch_items": "Zoning in Sun Valley and Pacoima's industrial pockets runs M1 through M3 depending on the block, with MR1/MR2 buffer zoning appearing where industrial parcels sit closest to residential streets, narrowing use and tightening noise standards accordingly. Outdoor storage and yard-based uses common to recycling and building-materials operators draw closer entitlement scrutiny than an enclosed distribution building would. Most buildings in this pocket fall well under the roughly 100,000-square-foot threshold that triggers SCAQMD's WAIRE Program, though buyers of the larger distribution buildings that do exist here should confirm applicability before underwriting. Because so much of the tenant base is owner-occupied, buyers should also verify that existing outdoor and yard uses are properly permitted.",
        "faqs": [
            {"q": "What kind of businesses operate out of Sun Valley and Pacoima's industrial buildings?", "a": "Sun Valley and Pacoima house a more utilitarian tenant mix than most Los Angeles industrial submarkets: metal and construction-material recyclers, building-material yards and suppliers, auto-related and equipment-service businesses, light manufacturers, and local distribution operators. Much of the building stock is older and smaller-bay, built for function rather than image, which keeps the basis well below what a buyer would pay in the media-adjacent industrial pockets closer to Burbank or the larger distribution nodes elsewhere in the Valley. That combination of lower cost and steady blue-collar tenant demand has made this corner of the northeast San Fernando Valley one of the more accessible entry points for owner-users and value-add investors in the county, particularly for buyers who cannot compete for newer, larger buildings elsewhere."},
            {"q": "Is SBA financing a good fit for a recycling or building-materials business buying property in Sun Valley or Pacoima?", "a": "It usually is, and it is the financing path Commercial Lending Solutions sees most often in this pocket of the Valley. SBA 504 and 7(a) loans let an owner-user finance a building with less cash down than a conventional loan alone would require, and they can also fund site improvements like paving, fencing, or yard upgrades that outdoor-storage and recycling operations frequently need. Lenders will underwrite the operating business alongside the real estate, looking at cash flow, time in business, and how the property is actually used, since yard-based and outdoor-storage uses draw more attention during entitlement and lending review than a standard enclosed building would. A bridge loan can cover the gap when a buyer needs to close before permanent SBA financing is in place."},
        ],
        "seo": {
            "h1": "Sun Valley & Pacoima Industrial Financing",
            "title": "Sun Valley & Pacoima Industrial Financing | CLS CRE",
            "meta_description": "Owner-user, SBA, and bridge financing for recycling, building-materials, and light-manufacturing properties in Sun Valley and Pacoima.",
        },
    },
]


def build_hoods() -> list:
    return RAW_HOODS


def build_hood_groups(hoods: list) -> list:
    """Group hoods by region, ordered per REGION_ORDER."""
    by_region = {}
    for h in hoods:
        by_region.setdefault(h["region"], []).append(h)
    groups = []
    for region in REGION_ORDER:
        if region in by_region:
            groups.append({"region": region, "hoods": by_region[region]})
    return groups


def nearby_hoods(hoods: list, current_slug: str, current_region: str, n: int = 4) -> list:
    """Up to n other hoods in the same region, excluding current; falls back
    to a rotating window of other hoods when the region is small, so pages
    in single-hood regions do not all surface the same list-order prefix
    (that would leave later hoods with zero inbound "nearby" links from
    any other detail page)."""
    same_region = [h for h in hoods if h["region"] == current_region and h["slug"] != current_slug]
    if len(same_region) >= n:
        return same_region[:n]
    others_pool = [h for h in hoods if h["region"] != current_region and h["slug"] != current_slug]
    if not others_pool:
        return same_region
    idx = next((i for i, h in enumerate(hoods) if h["slug"] == current_slug), 0)
    start = idx % len(others_pool)
    rotated = others_pool[start:] + others_pool[:start]
    need = n - len(same_region)
    return same_region + rotated[:need]
