"""
Los Angeles retail financing vertical -- 9 curated corridors.

Feeds la_retail_page.html and la_retail_index.html at /retail/la/{slug}.html
(round 2, authored 2026-07-11 via parallel agent fan-out against a
fact-checked LA retail regulatory brief: City of LA C1/C2/C4/CM zoning,
CUP requirements for drive-thru and alcohol uses, named corridor character).
Same shape as la_vertical.py's RAW_HOODS/build_hoods()/build_hood_groups()/
nearby_hoods() so generate.py wiring is identical between verticals.
"""

REGION_ORDER = ["Central LA", "Hancock Park & Larchmont", "Westside", "San Fernando Valley", "Downtown LA", "Beverly Hills", "Citywide"]

RAW_HOODS = [
    {
        "name": "Melrose Avenue & Fairfax District",
        "slug": "melrose-fairfax-retail",
        "region": "Central LA",
        "product_type": "Independent fashion, streetwear, and destination retail",
        "overview": "Melrose Avenue between La Brea and Fairfax, spilling into the blocks approaching West Hollywood, is one of the most recognizable retail streets in Los Angeles, and one of the most fragmented in terms of ownership. The building stock is old and small-format: single-story and two-story commercial buildings from the 1920s through the 1950s, narrow twenty-five and fifty-foot-wide parcels, and storefronts built for foot traffic rather than car access. Tenant mix runs toward independent fashion boutiques, streetwear and sneaker retailers, vintage and resale shops, tattoo studios, and destination coffee and food concepts that draw both locals from the Fairfax District and Beverly Grove and a steady stream of tourists and out-of-town buyers.\n\nOwnership is mostly private and long-held. Many buildings have sat with the same family or small partnership for decades, which means turnover, when it happens, is a genuine opportunity rather than a routine trade. Leases tend to be straightforward retail gross or NNN structures rather than the percentage-rent deals seen in larger shopping centers, since most tenants are single-location independents, not national chains. What separates Melrose from a corridor like Larchmont a few miles east is tone: this is a trend-driven, edgier fashion and culture street, not a family village center, and rents get bid up by tenants who need to be seen here specifically, not just anywhere in the Fairfax District.",
        "financing_playbook": "Buildings on Melrose trade in a fairly tight lane, roughly $1 million up to $15 million for most single-tenant and multi-tenant retail buildings, which puts most deals squarely in bridge and conventional bank territory rather than life company or CMBS-scale financing. Regional and community banks, credit unions, and private bridge lenders are the active capital sources, especially for value-add buys where a new owner is repositioning tenant mix or extending a short-term lease into a longer-term deal. We arrange both acquisition bridge loans for investors buying occupied or partially vacant buildings and permanent takeout financing once income stabilizes. Owner-user purchases, an independent retailer buying its own storefront, happen here too, usually financed through SBA 504 or 7(a) structures, though investor purchases still lead the corridor.",
        "watch_items": "Melrose sits within the City of LA's standard commercial corridor zoning, typically C2 or C4-type designations that vary parcel by parcel, so zoning should always be confirmed for the specific building rather than assumed from the block. As the tenant mix has shifted toward more restaurants, wine bars, and evening-hours concepts, conditional use permit review for alcohol sales and late-hour operation has become a more frequent part of leasing and repositioning here than when the street was purely retail. Parking is tight by nature of the old building stock, on-site parking is limited or nonexistent on many parcels, and buyers should plan around street parking and nearby lots rather than assume ratios that a newer suburban center would carry.",
        "faqs": [
            {"q": "What loan sizes are typical for retail buildings on Melrose Avenue?", "a": "Most Melrose Avenue retail buildings are small by commercial real estate standards, a single storefront or a handful of them, which keeps typical loan requests in the $1 million to $15 million range, with larger full-block assemblages going higher still or a larger multi-tenant building. CLS CRE's minimum loan size is $1 million, so this corridor fits comfortably within our normal lending box. We arrange acquisition bridge loans for investors buying occupied or partially vacant buildings, permanent financing once a tenant roster stabilizes, and owner-user financing for independent retailers purchasing their own storefront. Because ownership here is fragmented and mostly private, financing timelines often move quickly once a deal is identified."},
            {"q": "Is Melrose Avenue retail a good fit for SBA financing?", "a": "It can be, for the right buyer. SBA 504 and 7(a) financing generally works best when a business intends to occupy a majority of the building it buys, and on Melrose that describes an established independent retailer, restaurant, or service concept purchasing its own storefront rather than continuing to pay rent. That said, most activity on this corridor is investor-driven, buyers acquiring a building to lease to independent tenants, which points toward conventional bank or bridge financing instead. We evaluate both paths and will walk an owner-user buyer through SBA structuring, or point an investor toward the bridge and permanent options that fit a leased, income-producing Melrose Avenue building."},
        ],
        "seo": {
            "h1": "Melrose Avenue & Fairfax District Retail Property Financing",
            "title": "Melrose Avenue & Fairfax District Retail Financing | CLS CRE",
            "meta_description": "Acquisition, bridge, and SBA financing for independent fashion and streetwear retail buildings on Melrose Avenue and the Fairfax District. CLS CRE, $1M+.",
        },
    },
    {
        "name": "Larchmont Boulevard (Larchmont Village)",
        "slug": "larchmont-village-retail",
        "region": "Hancock Park & Larchmont",
        "product_type": "Boutique village retail",
        "overview": "Larchmont Boulevard runs a short, low-rise stretch through Larchmont Village, tucked between Hancock Park and Windsor Square just north of the Wilshire corridor. It reads more like a small-town main street than a Los Angeles retail corridor: one- and two-story buildings, wide sidewalks, mature trees, and a tenant roster built around daily-needs and lifestyle retail rather than fashion-forward statement stores. Coffee shops, bookstores, children's boutiques, salons, a produce stand, bakeries, and locally owned restaurants make up the bulk of the street, serving the surrounding single-family neighborhoods as much as any outside visitor.\n\nThat family-oriented, walkable character is what separates Larchmont from a corridor like Melrose Avenue a few miles west. Melrose pulls a fashion and streetwear crowd looking to be seen; Larchmont serves the households of Hancock Park and Windsor Square on a Saturday morning. Building stock is older and low-rise, and turnover is infrequent because tenants tend to stay for years once they find a fit with the neighborhood. A short drive from the Hollywood studio lots to the north via Melrose Avenue and a few blocks from the Wilshire Boulevard corridor and Metro's D Line, Larchmont's retail buildings are prized by long-term holders more than by value-add flippers.",
        "financing_playbook": "Larchmont's small footprint of retail buildings rarely trades, and when it does, deal sizes usually land in the $1 million to $8 million range for a single building or small row of storefronts. Because tenants here are stable, long-tenured, and low-risk, conventional bank and credit union financing is the default, with bridge debt reserved for the occasional vacancy or ownership transition that needs a short runway before permanent financing. We see more permanent and cash-out refinance requests on this corridor than ground-up repositioning plays, reflecting how little the tenant mix turns over. Owner-user financing is uncommon since most Larchmont storefronts are leased rather than operator-owned, though it does happen for an established local business buying its own building.",
        "watch_items": "Larchmont sits within standard City of LA commercial zoning for a low-rise village corridor, and like any LA commercial street, conditional use permit review applies to any tenant seeking alcohol service or later operating hours, which matters here as the restaurant and wine-bar mix has grown. Parking is genuinely tight, the corridor was built for a pre-car era of neighborhood shopping, and buyers should expect reliance on street parking and small municipal lots rather than dedicated on-site parking. Because the neighborhood is protective of Larchmont's scale and character, any redevelopment or use change tends to draw more community attention than a comparable change would on a purely commercial strip.",
        "faqs": [
            {"q": "How does financing for Larchmont Village retail differ from a corridor like Melrose Avenue?", "a": "The underlying loan process is similar, bridge or bank debt sized to the property's income and condition, but the risk profile reads differently to a lender. Larchmont's tenants are typically long-tenured local businesses serving a stable, affluent residential base in Hancock Park and Windsor Square, which lenders view as lower turnover risk than Melrose Avenue's more fashion- and trend-driven tenant mix. That often translates into more competitive terms from conventional banks and credit unions rather than a bridge-heavy financing path. CLS CRE still underwrites both corridors the same way, tenant quality, lease terms, and building condition first, but Larchmont deals tend to be simpler stories to tell a permanent lender."},
            {"q": "What loan minimum applies to a Larchmont Village retail purchase?", "a": "Our minimum loan size is $1 million, which comfortably covers the typical Larchmont Village retail building, whether that is a single storefront or a small multi-tenant row. Most purchases and refinances on this corridor fall in the $1 million to $8 million range. Because turnover is infrequent and buildings are tightly held, we see more refinance and cash-out requests here than ground-up acquisition financing, and we structure permanent debt around the corridor's low-vacancy, long-lease-term reality rather than treating it like a value-add play."},
        ],
        "seo": {
            "h1": "Larchmont Village Retail Property Financing",
            "title": "Larchmont Village Retail Financing | CLS CRE",
            "meta_description": "Bridge, permanent, and refinance financing for boutique retail buildings on Larchmont Boulevard near Hancock Park. CLS CRE, $1 million minimum loan size.",
        },
    },
    {
        "name": "Abbot Kinney Boulevard (Venice)",
        "slug": "abbot-kinney-venice-retail",
        "region": "Westside",
        "product_type": "Destination lifestyle and design retail",
        "overview": "Abbot Kinney Boulevard runs a little more than a mile through Venice, from the traffic circle near Venice Boulevard down toward Washington Boulevard, and it has become one of the most sought-after retail addresses on the Westside. The tenant mix leans toward design showrooms, home goods, independent fashion, art galleries, and destination restaurants and cafes, the kind of retail that draws a visitor specifically to that address rather than picking it up along the way. Building stock is a mix of converted early-20th-century bungalows, small commercial buildings, and newer infill retail construction, almost all low-rise and pedestrian-scaled.\n\nFoot traffic is heavily tourism- and visitor-driven, fed by Venice Beach, the Venice canals, and Main Street in neighboring Santa Monica, on top of a dense, affluent residential base in Venice itself and nearby Marina del Rey. That visibility and visitor volume have pushed asking rents on Abbot Kinney into some of the highest on the Westside. A short drive from the 10 freeway by way of Lincoln Boulevard or Venice Boulevard, the corridor's appeal is less about car access and more about being a walkable, curated destination that a retailer wants on its resume.",
        "financing_playbook": "Abbot Kinney's combination of small building footprints and premium rents produces high per-square-foot values, so loan requests skew toward the $2 million to $20 million range even for a modest-sized building, with larger assemblages going higher. Life insurance company and CMBS lenders will look at stabilized, well-leased buildings here given the rent profile, but most acquisition and value-add activity still runs through bank and private bridge financing, particularly when a buyer is repositioning tenant mix or has near-term lease rollover to manage. We most often see investor purchases on this corridor rather than owner-users, since the retail rents here generally price out a small operator from owning outright, though SBA financing remains an option for an established, well-capitalized local business.",
        "watch_items": "Venice sits within the California Coastal Zone, which means most exterior work, redevelopment, or a meaningful change of use on Abbot Kinney requires Coastal Development Permit review on top of the City of LA's standard commercial zoning, a materially longer and more involved entitlement path than inland LA retail corridors. Conditional use permit review also applies to tenants seeking alcohol service, which is relevant given how much of the corridor's draw is restaurant- and bar-driven. Parking is a real constraint, the corridor was built out with converted residential-scale buildings and small commercial structures that were never designed around large surface lots, so most tenants and customers depend on street parking and nearby public lots. Given how tourism-dependent the foot traffic is, buyers should also weigh how a tenant's concept performs on weekdays versus the weekend and holiday crowds the corridor is known for.",
        "faqs": [
            {"q": "Why do Abbot Kinney retail buildings command higher loan amounts than other Venice-area properties?", "a": "Rents on Abbot Kinney are among the highest of any Westside retail corridor, driven by heavy tourism and visitor foot traffic from Venice Beach, the Venice canals, and neighboring Main Street in Santa Monica. Higher rents support higher valuations, which pushes typical loan requests well above the $1 million CLS CRE minimum, often into the $2 million to $20 million range depending on building size. Lenders also tend to underwrite these buildings more like a premier luxury-corridor asset than a standard neighborhood retail building, weighing tenant caliber and lease strength carefully given how much of the value sits in the rent roll rather than the dirt."},
            {"q": "Is Abbot Kinney a landlord's market or an owner-user market for retail buyers?", "a": "Overwhelmingly a landlord's market. Most Abbot Kinney retail buildings are owned by investors and leased to independent design, fashion, and restaurant tenants rather than occupied by an owner-operator. The rent levels that make this corridor attractive to investors also make outright ownership a stretch for many small operators, so most financing here is investor acquisition or refinance debt rather than SBA owner-user lending. We do see SBA financing occasionally for an established, well-capitalized local business ready to buy rather than lease, but it is the exception on this corridor, not the rule."},
        ],
        "seo": {
            "h1": "Abbot Kinney Boulevard Retail Financing",
            "title": "Abbot Kinney Retail Property Financing | CLS CRE",
            "meta_description": "Financing for Abbot Kinney Boulevard retail buildings in Venice, one of the Westside's highest-rent corridors. Bridge, permanent, and investor financing.",
        },
    },
    {
        "name": "Ventura Boulevard (Sherman Oaks, Encino, Woodland Hills, Studio City, Tarzana)",
        "slug": "ventura-boulevard-retail",
        "region": "San Fernando Valley",
        "product_type": "Suburban strip-center and freestanding pad retail",
        "overview": "Ventura Boulevard is the San Fernando Valley's dominant retail spine, running for miles roughly parallel to the 101 freeway through Studio City, Sherman Oaks, Encino, Tarzana, and into Woodland Hills. Unlike the walkable, pedestrian-first corridors on the Westside and in Central LA, Ventura Boulevard is fundamentally car-dependent suburban retail: strip centers with surface parking, freestanding pad buildings, and a tenant mix built around convenience and daily needs rather than destination shopping. Quick-service restaurants, drive-thrus, banks, medical and dental offices, salons, fitness concepts, and local and regional service retailers make up most of the corridor, anchored at intervals by larger grocery- or drugstore-anchored centers.\n\nThe boulevard crosses the 405 at Sherman Oaks and passes major canyon routes, Coldwater Canyon, Laurel Canyon, and Topanga Canyon Boulevard among them, that feed traffic down from the hillside neighborhoods on both sides. Building stock ranges from older, smaller strip centers built in the 1960s through the 1980s to newer pad developments and redeveloped centers, and ownership is a genuine mix of long-term family holders, regional investors, and single-tenant owner-operators. This is a fundamentally different retail product from Melrose Avenue or Abbot Kinney: less about foot traffic and street presence, more about visibility from the car, drive-time convenience, and consistent daily traffic counts across a corridor that runs nearly the length of the Valley.",
        "financing_playbook": "Ventura Boulevard sees the broadest range of deal types of any LA retail corridor that we finance, from a $1 million single-tenant pad building up to a $20 million-plus multi-tenant strip center. Investor acquisitions and refinances of leased strip centers lead the volume, financed through banks, credit unions, and bridge lenders depending on occupancy and condition, with life company and CMBS execution available for larger, stabilized centers. But because so much of the boulevard's product is freestanding pad buildings, single-tenant restaurants, auto-service uses, medical and dental offices, gyms, this is one of the more genuinely owner-user-heavy retail corridors in Los Angeles. SBA 504 and 7(a) financing plays a real role here, letting an operator buy the real estate under their own business rather than lease it, alongside the investor-driven strip center financing that still makes up the bulk of the corridor.",
        "watch_items": "Ventura Boulevard's commercial parcels fall under the City of LA's standard commercial zoning framework, and given how many pad users here are quick-service restaurants, drive-thrus, and other auto-oriented concepts, conditional use permit review for drive-thru operations and alcohol sales comes up regularly, more so than on a pure foot-traffic corridor. Parking is rarely the constraint it is on Melrose or Larchmont since most centers were built with surface lots to match suburban car-dependent demand, though older centers can still be under-parked relative to a modern redevelopment. Because the corridor spans multiple Valley neighborhoods, from Studio City to Woodland Hills, character and rent levels vary meaningfully block to block, and each stretch should be underwritten on its own terms.",
        "faqs": [
            {"q": "Is Ventura Boulevard a good fit for SBA owner-user financing?", "a": "Yes, more so than most LA retail corridors. A meaningful share of Ventura Boulevard's product is freestanding pad buildings, single-tenant restaurants, auto-service uses, medical and dental offices, fitness concepts, that are naturally suited to an operator buying the real estate under their own business rather than leasing it. SBA 504 and 7(a) structures fit that pattern well. That said, the boulevard's larger strip centers are still predominantly investor-owned and leased to multiple tenants, so conventional bank, bridge, and permanent financing remain the biggest share of loan volume overall. CLS CRE underwrites both paths and can usually tell early in a conversation which structure fits a given Ventura Boulevard property."},
            {"q": "What loan sizes are typical for Ventura Boulevard retail properties?", "a": "It is the widest range of any corridor we finance in Los Angeles. A single freestanding pad building might be a $1 million to $3 million loan, right at our minimum, while a multi-tenant strip center or grocery-anchored center can run $10 million to $20 million or more. The boulevard's length, it runs through Studio City, Sherman Oaks, Encino, Tarzana, and Woodland Hills, means building size, tenant mix, and rent levels vary block to block, so we underwrite each Ventura Boulevard property on its own numbers rather than a corridor-wide assumption."},
        ],
        "seo": {
            "h1": "Ventura Boulevard Retail Property Financing",
            "title": "Ventura Boulevard Retail Financing | CLS CRE",
            "meta_description": "Bridge, permanent, and SBA financing for Ventura Boulevard strip centers and freestanding pad retail across Sherman Oaks, Encino, and Woodland Hills.",
        },
    },
    {
        "name": "Downtown Los Angeles (Broadway Theatre District, Fashion District, Arts District)",
        "slug": "downtown-la-retail",
        "region": "Downtown LA",
        "product_type": "Historic wholesale, fashion, and adaptive-reuse ground-floor retail",
        "overview": "Downtown LA's retail fabric splits across a few distinct but connected pockets. The Broadway Historic Theatre District, running the length of Broadway through downtown's Historic Core, holds one of the largest concentrations of early-20th-century movie palaces in the country, many now repurposed as event space, retail, or church use beneath upper floors converted to residential lofts. A few blocks south and east, the Fashion District, centered on the Santee Alley area and running toward Wall and San Pedro Streets, remains a dense wholesale and cut-and-sew garment hub, with ground-floor retail and showroom space stacked block after block. East across Alameda Street, the Arts District has layered new ground-floor retail, coffee, design, and food concepts into what was overwhelmingly industrial and warehouse building stock only a decade or two ago.\n\nWhat ties these pockets together is adaptive reuse. Across all three, retail increasingly sits at the base of buildings originally built for something else, a theatre, a garment factory, a warehouse, now carrying apartments or offices above. Downtown Los Angeles is framed by the 110 freeway to the west, the 101 to the north, and the 10 to the south, with the 5 running not far to the east, and Metro's A, B, D, and E Lines converging at 7th St/Metro Center downtown while Union Station anchors rail access at the north end near the Arts District and Little Tokyo. Tenant mix ranges from legacy wholesale operators who have been in the Fashion District for decades to new-to-market retail and food concepts chasing downtown's growing residential base.",
        "financing_playbook": "Downtown LA retail financing depends heavily on which pocket a building sits in. Fashion District buildings, often combining ground-floor retail or showroom space with upper-floor wholesale or light-manufacturing use, tend to be valued and financed like a hybrid retail-industrial asset, typically $1 million to $10 million for a single building. Broadway Theatre District and Arts District ground-floor retail, especially where it sits beneath a converted residential or office building, is usually financed alongside or subordinate to the larger adaptive-reuse project rather than as a standalone retail loan. We see bank and bridge lending lead this market, with CMBS and life company capital reserved for larger, stabilized mixed-use buildings. Investor ownership dominates; owner-user activity is limited mostly to established Fashion District wholesale operators buying their own building.",
        "watch_items": "Zoning across Downtown LA retail includes Commercial Manufacturing (CM) designations in parts of the Fashion District, which explains why ground-floor retail and showroom space sit comfortably alongside light industrial and wholesale cutting-room use in the same buildings, a mix a purely commercial C1 or C2 designation would not support. Conditional use permit review for alcohol sales and late-hour operation is a frequent part of leasing in the Arts District and around the Broadway corridor, given how much of the recent retail growth is bar- and restaurant-driven. Because so much of downtown's retail sits beneath adaptive-reuse residential or office conversions, buyers should underwrite how tightly the retail space's performance ties to the building's lease-up and occupancy above it.",
        "faqs": [
            {"q": "How does financing differ between the Fashion District and the Arts District?", "a": "The Fashion District's buildings typically combine ground-floor retail or showroom space with upper-floor wholesale and light-manufacturing use, so lenders often value and underwrite them as a hybrid retail-industrial asset rather than pure retail, with Commercial Manufacturing zoning supporting that mixed use. Arts District ground-floor retail, by contrast, usually sits beneath a converted residential or office building and gets financed as part of that larger adaptive-reuse project rather than as its own standalone loan. CLS CRE structures financing around whichever reality applies, standalone acquisition or refinance debt for a Fashion District wholesale-retail building, or retail-component financing folded into a larger downtown adaptive-reuse deal for an Arts District address."},
            {"q": "Who typically buys retail property in Downtown LA?", "a": "Mostly investors, and mostly people who already understand the neighborhood. Fashion District buyers are frequently established wholesale or garment-adjacent operators purchasing a building they already lease space in, while Broadway Theatre District and Arts District retail more often trades as part of a larger adaptive-reuse investment, sometimes led by developers converting the upper floors to residential or office use. Our minimum loan size is $1 million, and most Downtown LA retail financing we arrange runs from there up into the double-digit millions depending on building size and whether the deal includes an adaptive-reuse component above the retail space."},
        ],
        "seo": {
            "h1": "Downtown Los Angeles Retail Property Financing",
            "title": "Downtown LA Retail Financing | CLS CRE",
            "meta_description": "Financing for Downtown Los Angeles retail: Fashion District wholesale-retail buildings, Broadway Theatre District, and Arts District ground-floor space.",
        },
    },
    {
        "name": "Westwood Village",
        "slug": "westwood-village-retail",
        "region": "Westside",
        "product_type": "University-driven retail and food service",
        "overview": "Westwood Village sits directly against the UCLA campus at the base of the Wilshire corridor, bounded roughly by Wilshire Boulevard, Westwood Boulevard, and Le Conte Avenue, with the San Diego Freeway (I-405) running along the neighborhood's western edge. The Village's retail stock is mostly low-rise, prewar and mid-century buildings built for pedestrian storefronts rather than big-box format, ground-floor restaurant, fast-casual, and service tenants sitting below older office space and a handful of historic theater buildings.\n\nWhat sets Westwood apart from other Los Angeles retail corridors is the demand base next door: tens of thousands of UCLA students, faculty, and staff who work, live, and eat within walking distance year-round, plus the Village's role as a satellite dining and retail node for the broader Westwood and Wilshire corridor office and medical uses nearby. Tenant mix leans heavily toward food service, quick-service, boba, ramen, coffee, alongside student-oriented retail, personal services, and a scattering of longer-format sit-down restaurants. The corridor has cycled through visible storefront vacancy in past years, the way any pedestrian retail district does, but the underlying demand driver is structurally different from corridors that depend on discretionary or tourist spending: a captive student and staff population that renews every fall regardless of the broader retail or office market cycle, supporting occupancy stability through periods that hit other corridors much harder.",
        "financing_playbook": "Financing across Westwood Village retail runs mostly through conventional bank and credit union permanent debt for stabilized, multi-tenant buildings leasing to UCLA-driven food service and retail tenants, alongside bridge loans for buyers repositioning a vacant or under-leased storefront ahead of a permanent takeout. CMBS and life company execution shows up on larger, fully-leased buildings where in-place income supports a longer hold. Because most Westwood Village retail trades as multi-tenant investment property rather than owner-occupied space, SBA owner-user financing is a smaller share of the mix here than in freestanding strip-center or pad locations elsewhere in Los Angeles, though it still appears when a restaurant or service operator buys its own building. CLS CRE arranges these loans starting at a $1 million minimum, scaling with building size from a single storefront acquisition up to a multi-tenant building spanning a full block frontage.",
        "watch_items": "Westwood Village's retail buildings were largely built before modern parking requirements, so on-site parking is limited and most tenants and customers rely on street parking and nearby public or shared structures, a constraint any buyer or lender should underwrite around rather than assume away. Any restaurant or bar pursuing alcohol service, or a late-hour use, should expect the conditional use permit review that Los Angeles commercial zones commonly require for those uses, and that entitlement timeline belongs in the underwriting and leasing schedule from day one. Zoning across the Village follows the city's standard commercial designations and should be verified parcel by parcel rather than assumed from a neighboring building.",
        "faqs": [
            {"q": "What makes Westwood Village retail different from other Los Angeles retail corridors?", "a": "Westwood Village's defining advantage is proximity to UCLA. Unlike corridors that depend on discretionary shopping, tourism, or office worker lunch traffic, Westwood Village draws a captive base of students, faculty, and staff who live, study, and work within walking distance every day the university is in session. That demand base is far less sensitive to broader retail trends or economic cycles than a fashion-driven or tourist-driven corridor, which is why food service and student-oriented retail have remained the dominant tenant categories here for decades. For lenders and investors, that translates into a demand story that is easier to underwrite through a full hold period, even when individual storefronts turn over."},
            {"q": "What financing options fit a Westwood Village retail acquisition?", "a": "Most Westwood Village retail financing is acquisition or bridge debt on multi-tenant buildings, since the corridor's product is mostly older, pedestrian-scale retail leased to several food service and retail tenants rather than a single owner-occupant. A stabilized, well-leased building typically fits conventional bank, credit union, or life company permanent financing, while a building with vacancy or near-term lease rollover often starts with a bridge loan sized to carry lease-up before refinancing into permanent debt. Loan sizes start at a $1 million minimum and scale with the building, and SBA owner-user financing remains available on the occasional deal where an operator is buying its own space."},
        ],
        "seo": {
            "h1": "Westwood Village Retail Property Financing",
            "title": "Westwood Village Retail Property Financing | CLS CRE",
            "meta_description": "Commercial Lending Solutions arranges acquisition, bridge, and permanent financing for Westwood Village retail near UCLA, from a $1 million minimum.",
        },
    },
    {
        "name": "Beverly Hills Golden Triangle",
        "slug": "beverly-hills-golden-triangle-retail",
        "region": "Beverly Hills",
        "product_type": "Luxury flagship retail",
        "overview": "The Beverly Hills Golden Triangle, roughly bounded by Wilshire Boulevard, Santa Monica Boulevard, and Crescent Drive, with Rodeo Drive, Beverly Drive, and Canon Drive running through its center, is the highest-profile luxury retail address in Los Angeles and among the highest-rent retail corridors in the country. Ground-floor space here leases almost exclusively to global luxury fashion houses, jewelers, and flagship brand showcases that treat a Golden Triangle store as a marketing statement as much as a sales location, which supports rents and asset values that have little in common with retail economics anywhere else in the city.\n\nBuildings tend to be small-footprint, low-rise structures on extremely valuable land, and ownership is dominated by long-hold institutional capital and family-office or multigenerational ownership groups rather than typical private investors buying and selling on a normal hold cycle. Transaction volume is genuinely low. Golden Triangle retail trades infrequently, and when it does, basis per square foot sits in a different tier from any other Los Angeles retail corridor, industrial park, or multifamily asset. For CLS CRE, the Golden Triangle represents the top of the Los Angeles retail basis spectrum, a small, tightly held market where financing conversations center on sponsor strength, note structure, and long-term hold intent rather than the leasing and repositioning questions that dominate most other Los Angeles retail corridors.",
        "financing_playbook": "Financing in the Golden Triangle looks different from the rest of CLS CRE's Los Angeles retail coverage. Buyers here are typically well-capitalized institutions, family offices, or multigenerational owners who use debt conservatively relative to the extreme basis per square foot, so loan requests skew toward lower-leverage, long-term fixed-rate permanent financing from life insurance companies, large banks, and CMBS execution against a well-credentialed luxury tenant lease. Bridge debt appears occasionally around ownership transitions, lease rollover, or the repositioning of a single flagship building, but it is the exception rather than the rule in a market this tightly held. Owner-user SBA financing has little role here, since flagship tenants lease their Rodeo Drive space rather than own the real estate under it. Every loan clears the $1 million minimum many times over; the real underwriting question is sponsor strength, not deal size.",
        "watch_items": "Beverly Hills is a separate incorporated city with its own zoning code and permitting authority, distinct from the City of Los Angeles, so any use change, alcohol license, or late-hour operation in the Golden Triangle runs through Beverly Hills' own planning and permitting review rather than the Los Angeles process described elsewhere in this guide. Parking is structured and metered rather than surface-lot format, consistent with the district's dense, pedestrian-oriented layout. Because land value is so concentrated, ownership changes and redevelopment proposals draw a level of design review and scrutiny well beyond a typical Los Angeles retail corridor, and any repositioning plan should build that review timeline in from the start.",
        "faqs": [
            {"q": "Why is Beverly Hills Golden Triangle retail so much more expensive than other LA retail corridors?", "a": "The Golden Triangle's value comes from what the address itself represents rather than typical retail fundamentals like population density or daily traffic counts. Global luxury brands lease Rodeo Drive and the surrounding blocks as a flagship marketing presence, which supports rents and land values among the highest in the country and disconnected from ordinary retail rent comparables anywhere else in Los Angeles. Combined with an extremely small physical footprint, tight zoning, and an ownership base that rarely sells, the result is a market where basis per square foot sits in its own category: low transaction volume, very high per-square-foot pricing, and a buyer pool limited mostly to institutions and family offices rather than typical private retail investors."},
            {"q": "Who finances Beverly Hills Golden Triangle retail acquisitions?", "a": "Golden Triangle buyers are almost always well-capitalized institutions, family offices, or multigenerational ownership groups, and the debt follows that profile: conservative leverage, long-term fixed-rate permanent financing from life insurance companies and large banks, and CMBS execution against a well-credentialed luxury tenant lease. Bridge financing shows up around ownership transitions or a single-building repositioning, but it is far less common here than in other Los Angeles retail corridors, since so little Golden Triangle real estate trades hands in a given year. Owner-user financing is rare, since the flagship tenants that occupy Rodeo Drive storefronts generally lease rather than own their space, leaving investment-grade permanent debt as the dominant financing type in this corridor."},
        ],
        "seo": {
            "h1": "Beverly Hills Golden Triangle Retail Property Financing",
            "title": "Beverly Hills Golden Triangle Retail Financing",
            "meta_description": "Financing guidance for Beverly Hills Golden Triangle and Rodeo Drive retail real estate: institutional and family-office ownership, low-leverage permanent debt, and bridge financing for repositioning.",
        },
    },
    {
        "name": "Grocery-Anchored Neighborhood Centers",
        "slug": "grocery-anchored-retail-la",
        "region": "Citywide",
        "product_type": "Grocery-anchored neighborhood centers",
        "overview": "Grocery-anchored neighborhood centers are one of the most consistent retail property types active across Los Angeles, and unlike the corridors above, this product type is not tied to a single neighborhood. It shows up in nearly every submarket, from the San Fernando Valley to the South Bay to the San Gabriel Valley to South Los Angeles, wherever there is enough rooftop density to support daily-needs retail. The defining feature is the anchor: a national or regional grocery chain that draws consistent, non-discretionary foot traffic regardless of broader economic conditions, surrounded by a line of smaller in-line shops, drugstores, fast-casual restaurants, personal-care and medical uses, dry cleaners, and other daily-errand tenants that lean on the grocer's traffic to fill their own stores.\n\nBuilding stock ranges from older, low-rise strip-center product built decades ago to more recently renovated centers with updated facades and parking layouts, but the underlying real estate logic holds across every submarket: a grocery-anchored center serves a needs-based trip, not a discretionary one. That is exactly why this product type tends to hold occupancy and leasing interest through recessions and retail downturns that hit fashion, restaurant, and lifestyle corridors much harder. For investors, the appeal is durability over glamour: dependable cash flow anchored by a credit tenant and a roster of in-line shops that benefit from that same daily traffic, rather than a trend-driven retail concept that can fall out of favor.",
        "financing_playbook": "Grocery-anchored centers are a favorite among life insurance companies, banks, credit unions, and CMBS lenders, because the credit and traffic profile of the anchor tenant de-risks the whole center and typically supports more competitive permanent financing terms than most other Los Angeles retail product types can command. CLS CRE sees this across deal sizes from single small centers just above the firm's $1 million minimum up to larger multi-tenant assets anchored by a full-size grocery box, with bridge financing stepping in when a buyer is repositioning in-line vacancy, working through an anchor lease renewal, or upgrading a dated center ahead of a permanent refinance. Because these centers are almost always multi-tenant investment property, the buyer pool skews toward investors rather than owner-users, though a single operator occasionally buys a smaller center to run alongside its own business. Loan sizing centers on in-place and projected income across the full tenant roster.",
        "watch_items": "Grocery-anchored centers sit across the full range of Los Angeles commercial zoning, from C1 and C2 corridors up to C4 and CM parcels, so the applicable zoning and parking requirements vary center by center and should always be confirmed at the parcel level rather than assumed from a typical layout. Surface parking ratios matter enormously to this product type, since daily-needs trips depend on easy, visible parking, and any redevelopment or pad addition should be underwritten against the center's existing parking count. If any in-line tenant or outparcel involves alcohol sales, a drive-thru, or a late-hour use, expect the conditional use permit review that Los Angeles commercial zones commonly require for those uses, and build that timeline into the underwriting.",
        "faqs": [
            {"q": "What makes grocery-anchored retail centers a stable investment across Los Angeles?", "a": "The anchor tenant is the whole story. A national or regional grocery chain draws a needs-based trip that happens on a weekly basis regardless of what the broader economy is doing, and that traffic supports every in-line shop around it, from a dry cleaner to a fast-casual restaurant to a nail salon. That combination of credit-tenant durability and daily, non-discretionary demand is why grocery-anchored centers tend to hold occupancy through downturns that hit fashion, restaurant, and lifestyle-driven retail much harder. It is also why life insurance companies, banks, and CMBS lenders treat grocery-anchored centers as some of the most financeable retail product in Los Angeles, across almost every submarket in the city."},
            {"q": "Does financing for a grocery-anchored center depend on which Los Angeles submarket it is in?", "a": "Less than most other retail property types. Because the investment thesis rests on the anchor tenant's credit and the daily-needs nature of the center rather than a specific neighborhood's retail identity, a well-leased grocery-anchored center in the San Fernando Valley, the South Bay, or the San Gabriel Valley underwrites on largely the same criteria: anchor lease strength, in-line tenant roster, parking adequacy, and overall net operating income. Location still affects value and rent levels, but it does not change the fundamental financing approach the way it does for a destination fashion corridor or a tourism-driven retail street. That consistency is part of why banks, credit unions, and life companies are comfortable financing this product type across nearly every Los Angeles submarket."},
        ],
        "seo": {
            "h1": "Grocery-Anchored Retail Center Financing, Los Angeles",
            "title": "Grocery-Anchored Retail Center Financing in Los Angeles",
            "meta_description": "Commercial Lending Solutions arranges acquisition, bridge, and permanent financing for grocery-anchored neighborhood retail centers across every Los Angeles submarket, from a $1 million minimum.",
        },
    },
    {
        "name": "Auto and QSR Pad Retail",
        "slug": "auto-qsr-pad-retail-la",
        "region": "Citywide",
        "product_type": "Auto and QSR pad sites",
        "overview": "Auto-related and quick-service pad retail, meaning gas stations, car washes, drive-thru restaurants, and other freestanding pad sites, is one of the most common property types CLS CRE actually closes across Los Angeles. Unlike a single retail corridor, it shows up on arterial boulevards and near busy intersections in nearly every submarket, from Ventura Boulevard in the San Fernando Valley to Pico and Sepulveda on the Westside to Vermont and Western in South Los Angeles.\n\nThese are almost always small-footprint, freestanding parcels built around a single use: a fuel canopy and pump islands, a car wash tunnel and vacuum bays, or a quick-service restaurant building with a drive-thru lane, usually sited on a corner or mid-block parcel with direct arterial access and dedicated ingress and egress for stacking. Ownership falls into two distinct buckets that behave very differently in an underwriting file: independent operators who buy the real estate to run their own gas station, car wash, or restaurant, and investors who buy a single-tenant building leased on a long-term, triple-net basis to a national or regional operator as a sale-leaseback or ground lease. Both buyer types are active across Los Angeles at any given time, and both show up regularly in the firm's closed-deal mix, which makes this one of the more dependable, recession-resilient property types in its Los Angeles book of business.",
        "financing_playbook": "Financing for auto and QSR pad retail splits cleanly along the owner-user and investor line. Owner-operators buying the real estate under their own gas station, car wash, or restaurant are frequent SBA 504 and 7(a) borrowers, since these are true operating businesses tied to real estate, and CLS CRE arranges that owner-user debt regularly alongside conventional bank financing. Investors buying a single-tenant, triple-net leased pad as a sale-leaseback or ground lease lean more on conventional bank, CMBS, or life company permanent debt underwritten to the lease term and tenant credit, with bridge financing appearing when a site needs re-tenanting, environmental work, or a rebuild before a long-term lease is in place. Deal sizes here often sit closer to the $1 million minimum than the larger multi-tenant retail centers elsewhere in the city, though multi-bay car washes and combined fuel-and-convenience sites can scale well beyond that floor.",
        "watch_items": "Both fuel-dispensing uses and drive-thru restaurants typically require conditional use permit review in Los Angeles commercial zones, so any acquisition or ground-up plan involving a gas station or a drive-thru lane should build that entitlement timeline into underwriting from the outset rather than treat it as a formality. Site design matters as much as zoning: drive-thru stacking and queuing, dedicated ingress and egress on a corner or arterial parcel, and adequate on-site circulation all affect operations and value alike. Underlying zoning runs through the city's standard commercial designations and should be confirmed parcel by parcel, since permitted uses and parking requirements differ by zone and by whatever conditional approvals a given site has accumulated over time.",
        "faqs": [
            {"q": "Does a gas station or drive-thru restaurant in Los Angeles require a conditional use permit?", "a": "Typically, yes. Fuel-dispensing uses and drive-thru restaurants commonly require conditional use permit review under Los Angeles commercial zoning, and that entitlement step should be built into any acquisition timeline or ground-up construction schedule from the start rather than treated as a late-stage formality. The specifics depend on the parcel's zoning designation and its entitlement history, since an existing gas station or drive-thru that has operated for years may carry approvals that a ground-up project would need to secure from scratch. Buyers and lenders underwriting these deals should confirm entitlement status early, especially on any acquisition where a change of use or a new drive-thru lane is part of the plan."},
            {"q": "Is auto and QSR pad retail typically an owner-user or investor deal?", "a": "Both, in roughly equal measure, which is part of what makes this product type distinct from most other Los Angeles retail. Independent operators regularly buy the real estate under their own gas station, car wash, or restaurant and finance it with SBA or conventional owner-user debt. Investors just as often buy a single-tenant building leased on a triple-net basis to a national or regional operator, financed with conventional bank, CMBS, or life company permanent debt and sometimes bridge financing around a re-tenanting or rebuild. Commercial Lending Solutions sees both profiles regularly across Los Angeles, from a single independent car wash owner to an investor acquiring a portfolio of triple-net leased pad sites."},
        ],
        "seo": {
            "h1": "Auto and QSR Pad Retail Financing, Los Angeles",
            "title": "Gas Station, Car Wash, and QSR Pad Site Financing, LA",
            "meta_description": "Financing for gas stations, car washes, and QSR drive-thru pad sites across Los Angeles: owner-user SBA loans and investor NNN sale-leaseback debt, from a $1 million minimum.",
        },
    },
]


def build_hoods() -> list:
    return RAW_HOODS


def build_hood_groups(hoods: list) -> list:
    """Group hoods by region, ordered per REGION_ORDER."""
    by_region = {}
    for h in hoods:
        by_region.setdefault(h["region"], []).append(h)
    groups = []
    for region in REGION_ORDER:
        if region in by_region:
            groups.append({"region": region, "hoods": by_region[region]})
    return groups


def nearby_hoods(hoods: list, current_slug: str, current_region: str, n: int = 4) -> list:
    """Up to n other hoods in the same region, excluding current; falls back
    to a rotating window of other hoods when the region is small, so pages
    in single-hood regions do not all surface the same list-order prefix
    (that would leave later hoods with zero inbound "nearby" links from
    any other detail page)."""
    same_region = [h for h in hoods if h["region"] == current_region and h["slug"] != current_slug]
    if len(same_region) >= n:
        return same_region[:n]
    others_pool = [h for h in hoods if h["region"] != current_region and h["slug"] != current_slug]
    if not others_pool:
        return same_region
    idx = next((i for i, h in enumerate(hoods) if h["slug"] == current_slug), 0)
    start = idx % len(others_pool)
    rotated = others_pool[start:] + others_pool[:start]
    need = n - len(same_region)
    return same_region + rotated[:need]
